### ISSUE TITLE
Improve the Developers' guide

### ISSUE THREAD

**Issue by TotallyNotChase** [Plutonomicon/plutarch-plutus#105]
Right now, the [Developers' guide](https://github.com/Plutonomicon/plutarch/blob/master/docs/DEVGUIDE.md) is quite barebones. Ideally it should explain all the concepts that Plutarch is built upon, under the hood. All the low level details about terms, `PDataRepr`, `PLift`, and more.

The following topics need to be covered, as a starting point:-
- [ ] `PConstant`/`PLift`. This should include all the low level details. Be sure to include info on `DefaultUni`. Though you can also use existing cross references as relevant.
- [ ] `PDataRepr`. This should include the following:-
  - [ ] Anatomy of the pattern matching in general and `DataReprHandlers`.
  - [ ] Anatomy of the derivers (generic and `PIsDataReprInstances`)
  - [ ] Anatomy of the field accessors
- [ ] `Term`/`ClosedTerm` and how code gen works in general. Ideally, it should provide some information on how Plutarch types are merely "tags", and their Haskell ADT hardly matters, and how these tags are actually used to "tag" concrete Plutus Core constants (or lambdas, for scott encoding).
- [ ] The machinery behind `PLam` (`plam`).

**Comment by srid** [comment]
See also #107

**Comment by TotallyNotChase** [comment]
I'll probably work on this issue post Plutarch 1.1. Self assigning for now.

**Comment by TotallyNotChase** [comment]
I added a task list to this. If you have sufficient familiarity with any of this topics, please feel free to contribute and help make the developers guide better!
