### ISSUE TITLE
plutarch-extra

### ISSUE THREAD

**Issue by Geometer1729** [Plutonomicon/plutarch-plutus#139]
At the meeting today we talked about creating a separate cabal project (probably in this repo) for libraries in Plutarch.

**Comment by kozross** [comment]
For what it's worth, my experience with `plutus-extra` suggest that multiple independent repoes, with one per sublibrary, is a much better idea than a megarepo.

**Comment by L-as** [comment]
> At the meeting today we talked about creating a separate cabal project (probably in this repo) for libraries in Plutarch.

What meeting?

**Comment by L-as** [comment]
> For what it's worth, my experience with plutus-extra suggest that multiple independent repoes, with one per sublibrary, is a much better idea than a megarepo.

Elaborate?

**Comment by Geometer1729** [comment]
> What meeting?

The sprint meeting this morning.

**Comment by Geometer1729** [comment]
Is this a just timezone thing and the meeting was last night for you or something? Or did I misunderstand the conversation?

**Comment by kozross** [comment]
Big repoes with multiple projects in them end up becoming quite unwieldy, especially when you have a large pool of overall contributors, but where most of them are focused only on one or two sub-libraries.

**Comment by L-as** [comment]
@Geometer1729 it's possible I'm forgetting the conversation.

In any case, @kozross I agree, but we're in a state where Plutarch changes rapidly. If `plutarch-extra` is in this repository, then the changes can happen together.

**Comment by Geometer1729** [comment]
I mentioned that plutarch is missing a lot of prelude analogs ie `pfst` and `psnd` for `PPair` and asked if you intended plutarch to eventually have functions like that and iirc it was your idea that there should be a separate module for library functions like that.

**Comment by L-as** [comment]
@Geometer1729 Those things should just be in `Plutarch.Pair`. It's more things like `Natural` that might want a separate library potentially.
