### ISSUE TITLE
Rewrite rules

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#260]
We want rewrite rules to support things like #128.

Rewrite rules should function like GHC's rewrite rules, albeit they should fire consistently. This is easier for us
to do because of the lack of complex optimisations.

**Comment by delicious-lemon** [comment]
Yes! Is there any work toward this ongoing? 

My motivation is https://github.com/mlabs-haskell/apropos-tx/blob/26294dbaa3a1c9e794bdeab2af98d2f74624ab96/src/Apropos/Script/Iso/Arrow.hs#L49

These combinators introduce unnecessary construction/deconstruction of builtin pairs which could be reduced easily by a rewrite.

**Comment by L-as** [comment]
I am working on this internally.

**Comment by srid** [comment]
- Having a rewrite rule to "drop" traces (as part of #359) which incidentally resolves #290

**Comment by blamario** [comment]
Just to be clear, are the rewrite rules supposed to operate on the compiled `Script`s like Shrinker does, or on a `Term`?

**Comment by L-as** [comment]
@blamario They operate on the precompilation AST.

**Comment by L-as** [comment]
I think I have a viable design FWIW

**Comment by srid** [comment]
What sort of optimizations will rewrite rules provide? 

Specifically, if I use `pfield @"txInfo" ctx` in more than one place, will that get optimized (ie, hoisted at top-level and gets used via reference, instead of recomputing)?

**Comment by L-as** [comment]
In some places however this means we have to do a `plet` and that's not free.

**Comment by L-as** [comment]
They're supposed to operate on Plutarch terms.
