### ISSUE TITLE
Use `TermCont` more

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#262]
This might conflict with #202 , unsure at this point.

**Comment by TotallyNotChase** [comment]
What do you mean? Use `TermCont` more where?

**Comment by L-as** [comment]
Anything that returns `(a -> Term s b) -> Term s b` should just use `TermCont s a`.

**Comment by blamario** [comment]
Rather than change the type of `pmatch` and other functions, it would be better to export their synonyms from `Plutarch.TermCont`.

**Comment by Geometer1729** [comment]
I find pmatch is still sometimes useful even using TermCont fairly heavily. I'd preffer a solution where both the original pmatch and something that uses TermCont are available. Currently we're using `tmatch = tcont. pmatch`, and that's been working pretty well.

**Comment by L-as** [comment]
Bad idea for Plutarch 1
