### ISSUE TITLE
Expose additional Cryptographic Hashing APIs

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/plutarch-plutus#271]
As with script hashing (#245)  there's some cryptographic functions which are necessary in many cases to construct or test scripts, which Plutus makes available only in `plutus-apps`. 

- `pubKeyHash` , which uses `Blake2b_224`
- `datumHash`, which uses `Blake2b_256`

In PlutusTx, we also have:
- `Sha2_256` & `Sha3_256`, which have builtins in PlutusTx. 

These aren't used for anything fundamental (afaik), but would be useful to expose APIs for incase they are relevant.

**Comment by TotallyNotChase** [comment]
We do have `psha2_256`, `psha3_256`, and `pblake2b_256` in `Plutarch.Crypto` already - might be helpful.

**Comment by L-as** [comment]
We should add these functions yeah
