### ISSUE TITLE
Remove flakiness in `fail` pattern match messages

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch-plutus#290]
This can happen as a result of just shifting the program by a line or two:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/3998/154170456-bf50b215-c985-478c-8574-a86996328825.png">

https://hercules-ci.com/accounts/github/Plutonomicon/derivations/%2Fnix%2Fstore%2Fvx3q5p6blavkkqaab5a4r3jvlharfmw8-test-ghc9-dev.drv/log?via-job=02f9845c-7185-48b7-800d-0dac66e9dad1

**Comment by L-as** [comment]
https://github.com/Plutonomicon/plutarch/pull/276#issuecomment-1041320034

We really need to replace the string in `fails` in tests.
