### ISSUE TITLE
Add PlutusTx numeric instances for `Term s PInteger`

### ISSUE THREAD

**Issue by blamario** [Plutonomicon/plutarch-plutus#298]
It's not the first time I get
```
test/Spec.hs:283:85: error:
    * No instance for (AdditiveSemigroup (Term s (PInteger @{S})))
        arising from a use of `+'
```

because I imported the wrong Prelude. We already have `instance Num (Term s PInteger)`, we should add the `PlutusTx.Prelude` class instances as well. It literally doesn't matter which (+) is in scope, the result will be exactly the same.

**Comment by TotallyNotChase** [comment]
Relevant PR: https://github.com/Plutonomicon/plutarch/pull/160
Relevant issue: https://github.com/Plutonomicon/plutarch/issues/139
