### ISSUE TITLE
Goldens get regenerated. 

### ISSUE THREAD

**Issue by MangoIV** [Plutonomicon/plutarch-plutus#330]
### steps to reproduce 
- run `cabal run plutarch-test` from the plutarch project root

### Expected behaviour
- the goldens only get generated in the `plutarch-test/goldens` folder 

### Actual behaviour 
- the goldens get generated in the `plutarch` project root.

**Comment by srid** [comment]
Oddly, ghcid (which I use instead of cabal) does put them in the right location:

```
ghcid -c 'cabal repl plutarch-test:exe:plutarch-test' -T Main.main
```
