### ISSUE TITLE
Semigroup instance for PUnit leaves args of  `<>` unevaluated

### ISSUE THREAD

**Issue by delicious-lemon** [Plutonomicon/plutarch-plutus#341]
https://github.com/Plutonomicon/plutarch/blob/d753dc34dfc30b144e94d6493c837ebd0c99b588/Plutarch/Unit.hs#L33

**Comment by TotallyNotChase** [comment]
hmm, I'm not sure the alternative is always better. This is one of those things that might be better handled with Plutarch 2.0's goals

**Comment by TotallyNotChase** [comment]
Not evaluating could be potentially useful depending on the context maybe? Although it _would_ be kinda silly for `PUnit`.

**Comment by delicious-lemon** [comment]
@TotallyNotChase my use case is I want to treat `PUnit` as a Truth value so it would be nice if  `<>` behaved like `AND`.

**Comment by TotallyNotChase** [comment]
one example I thought of where this impl could be considered useful is folding over a list of units with `<>`. Every element (all of those units) will indeed be evaluated anyway. However, with forceful evaluation within the `<>` body, it's sort of a redundant lambda application for each element. Not a big cost, but something to consider.

**Comment by L-as** [comment]
This has been fixed
