### ISSUE TITLE
Determine an ergonomic way to log an error on a failed pattern match in P.do

### ISSUE THREAD

**Issue by peter-mlabs** [Plutonomicon/plutarch-plutus#360]
I'd like to annotate most functions that can fail with the various `ptrace` functions available. In plutarch, these will get dynamically compiled out for production, so there is little reason not to do this.

However, it appears that `P.do` doesn't allow use to actually print error messages on a failed pattern match. It would be nice if there was a way to do so.

Something like 

```
f = P.do
  x <- pmatch something <?> "[f]: Match `something` failed."
```

**Comment by TotallyNotChase** [comment]
Do you mean when using partial pattern matches? like [here](https://github.com/Plutonomicon/plutarch/blob/master/plutarch-test/src/Plutarch/MonadicSpec.hs#L42). A message will be traced upon such a failure automatically, and the script will error. The specific message is determined by GHC but it's something in the lines of "pattern match failure at line:X:Y"

Do you want to customize this message?

**Comment by peter-mlabs** [comment]
Yes, I'd like to customize the message (if possible). We kept things pretty chatty on LiqwidX when we used PlutusTx to help debugging, and I'd like to do the same in Plutarch. Do you know if this is something that can be done?

**Comment by TotallyNotChase** [comment]
I think manually case matching is the only way due to how `MonadFail` works

**Comment by L-as** [comment]
This should be possible theoretically.

**Comment by peter-mlabs** [comment]
Closed -- is this possible now, or WONTFIX?

**Comment by SeungheonOh** [comment]
We are trying to push TermCont more the syntax rebinding.

**Comment by peter-mlabs** [comment]
Great, that makes sense. Thanks for the info!
