### ISSUE TITLE
Docs website improvements

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch-plutus#401]
- [ ] Use `slug` YAML metadata so that instead of a long URL like `/Typeclasses/PlutusType%2C%20PCon%2C%20and%20PMatch.html` we see `/plutustype-pcon-pmatch.html`.
- [ ] Replace `hs` with `haskell` as language in code blocks; this will make syntax highlighting work for all Haskell code snippets in the guide.
- [ ] Fix PR links; cf. https://github.com/Plutonomicon/plutarch/pull/398#issuecomment-1079233133

**Comment by L-as** [comment]
I think we should just rename the files to not have spaces and uppercase letters.

**Comment by mateusap1** [comment]
Not sure if I should put this here, but I think that this part in the [hoisting section](https://github.com/Plutonomicon/plutarch/blob/master/docs/Concepts/Hoisting.md#hoisting-operators)
> Choosing convenience over efficiency is difficult, but if you notice that your operator uses complex logic
Should be instead
> Choosing efficiency over convenience is difficult, but if you notice that your operator uses complex logic

Not a big deal, but got me confused on this part
