### ISSUE TITLE
Change from `perror` to `ptraceError` in all places it's feasable

### ISSUE THREAD

**Issue by MangoIV** [Plutonomicon/plutarch-plutus#403]
### Problem

Debugging would be a lot easier if we just had a trace "`ptail: error: empty list`"

### Solution  

- replace `perror` with informative `ptraceError`s

### Blockers 

- needs #260

**Comment by TotallyNotChase** [comment]
Should ideally list all (or at least, most) `perror` usages to `ptraceError`.

Also note that this issue is referring to the default implementation of `phead`/`ptail` provided in the `PListLike` typeclass.

**Comment by MangoIV** [comment]
makes sense. I think I will replace the description to use `ptraceError` in all places where perror is used currently

**Comment by srid** [comment]
@MangoIV Be wary of #290 which may need to be resolved first via #260.
