### ISSUE TITLE
`PListLike` utilities could be return type polymorphic in the list type

### ISSUE THREAD

**Issue by TotallyNotChase** [Plutonomicon/plutarch-plutus#416]
Consider `pmap`-
```hs
pmap :: (PListLike list, PElemConstraint list a, PElemConstraint list b) => Term s ((a :--> b) :--> list a :--> list b)
```
It produces the same list type as its input. Sometimes, I find myself using `pconvertLists` right after a list operation - essentially iterating twice, one for the actual operation and another for conversion.

I wonder if it'd be feasible to have-
```hs
pmap :: (PIsListLike list1 a, PIsListLike list2 b) => Term s ((a :--> b) :--> list1 a :--> list2 b)
```
This would eliminate the need of `pconvertLists` afterwards as everything will be done in one go. Since the body of `pmap` uses list polymorphic functions anyway.

I haven't actually benchmarked this change yet though,

**Comment by L-as** [comment]
This would be a form of "list fusion" I suppose.

**Comment by MangoIV** [comment]
I think this would actually be really helpful, I have encountered this a couple of times already and was always wondering whether this would be possible, nice idea @TotallyNotChase

**Comment by TotallyNotChase** [comment]
my only concern is that this'd probably make type inference painful for chained operations - you'd need to use type application for each intermediary I guess. Unless it type defaults or something similar.

**Comment by L-as** [comment]
Seems to me like pconvertLists should have a rewrite rule!

**Comment by L-as** [comment]
Another idea:
Is there ever a reason to return PBuiltinList?

**Comment by TotallyNotChase** [comment]
I've definitely used `PBuiltinList` returns in places, though I can't remember if all of them were strictly necessary. I could imagine someone building a data type to return in some utility function that does contain a builtin list member though.

**Comment by srid** [comment]
Related query:

One of the functions to port, and upstream, from plutus-ledger-api looks like:

```haskell
getContinuingOutputs :: Term s (PScriptContext :--> PBuiltinList PTxOut)
```

Do we always want `PBuiltinList` as output? Or does it make sense to have this function convert and return a scott-encoded list? How would all of this look in the context of this issue (#416)?

**Comment by MangoIV** [comment]
Crazy idea: 
```haskell
-- this is what pmap gets renamed to
pmapht :: (a :--> b) :--> l0 a :--> l1 b
pmapht = ...
pmap :: (a :--> b) :--> l a :--> l b
pmap = pmapbt 
```
this would give us backwards compat but at the same time make it possible to do the optimization easily? (`ht` stands for bad type inference)
