### ISSUE TITLE
Rename `POpaque` to `PUnit` and remove `PUnit`?

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#440]
It seems to me that the current `PUnit` is entirely useless. Anytime you have `pcon PUnit` or `pconstant ()`, it would be acceptable if the type was `POpaque` (which would be renamed to `PUnit`).

**Comment by TotallyNotChase** [comment]
Does that mean making `POpaque` be represented as the builtin unit type? Otherwise it doesn't make much sense to me.

**Comment by MangoIV** [comment]
I don't understand it either. I first thought that we have the rule 
`forall a. POpaque <: a` which obviously isn't true if `POpaque` is only represented as `PUnit`

**Comment by L-as** [comment]
We'd have `PSubtype PUnit a` then.

**Comment by L-as** [comment]
The point is that I've often seen people using `PUnit` where they should have used `POpaque` for efficiency.

**Comment by TotallyNotChase** [comment]
`POpaque` is more efficient than `PUnit`? Don't you need _something_ to use `popaque` on to even obtain a `POpaque` (currently)?

**Comment by L-as** [comment]
Yes but you often have that "something".

**Comment by L-as** [comment]
Compare `pconst # pcon PUnit # (x + y)` vs `popaque $ x + y`. The latter is far smaller.

**Comment by TotallyNotChase** [comment]
well, the `pconst` version evaluates the second arg, the `popaque` one doesn't - it'd be delegated to the caller, yeah?

If we're not going to make `POpaque` be represented by builtin unit - we should keep both and simply acknowledge this trick in the guide. No one expects to use a "unit value" like `popaque $ x + y` - let alone have a `PUnit` that's not actually unit in UPLC (that'd confuse the hell out of me).

So let's just have both and be very clear about optimization strategies in the guide (just like we treat other optimization strategies in the guide).

**Comment by L-as** [comment]
I'm not sure what you mean honestly. Both are semantically completely equivalent.

**Comment by L-as** [comment]
I can't think of a *single* case where you'd want to only allow `pcon PUnit :: Term s PUnit` rather than arbitrary `a :: Term s PUnit`.

**Comment by L-as** [comment]
AFAIU, units category theoretically are the terminal object, because there should be a morphism from every object to the terminal object. It would make sense thus for the morphism to be a no-op, rather than having it be `pconst # pcon PUnit`, which is not a no-op.

**Comment by L-as** [comment]
This change would in fact be backward-compatible, unless we don't do `type POpaque = PUnit`.

**Comment by TotallyNotChase** [comment]
Unsure but [this usecase](https://github.com/Plutonomicon/plutarch/issues/341) might be relevant.
What are we replacing `pcon PUnit` (and `pconstant ()`) by btw?

Also, for *ideal* usage of this new `PUnit`, people are expected to have another (hopefully already evaluated) value at hand and it's simply "weaken"-ed into `PUnit`?

What happens with "sub-validator" functions? These often either return `PUnit` or `perror` and the main validator crumbles up all the results to `fold` over. Do we make a semigroup instance that just evaluates both its arguments and nothing else? What about `PEq` - just unconditional truth return I assume?

And finally, do we get rid of a Plutarch equivalent of UPLC's builtin unit altogether then, and treat UPLC's builtin unit differently from this new `PUnit`?

I'd like to get some clarity on these and hopefully log them up on the guide if we must go through with this change. I'm ok with it either way but maybe it's a good idea to get some more input for this, ideally from those users who are writing a lot of Plutarch.

**Comment by L-as** [comment]
Nothing, `pcon PUnit` and `pconstant ()` would still be `Term s PUnit`

**Comment by L-as** [comment]
I don't think we need user input honestly, because it's *completely transparent*. There's nothing that changes from the perspective of the user.
The only adding will be the (currently hypothetical) `punit :: Term s a -> Term s PUnit` function will `punsafeCoerce` instead of `pconst # pcon Unit`.

**Comment by TotallyNotChase** [comment]
wait, so we still keep `pconstant ()` and `pcon PUnit` that actually use the builtin unit, but we just rename `popaque` to `punit`?

Wouldn't we still need to make sure people actually use `punit` then (hopefully by putting it in the guide)? In which case, this doesn't seem to achieve the end goal.

Anyway, if that's the change - there indeed shouldn't be any user facing changes as long as no one has been counting on `PUnit`'s UPLC representation to be the same across the board.

**Comment by L-as** [comment]
I hadn't considered removing `pconstant ()` and `pcon PUnit`, albeit you certainly could. We could just recommend that people always use `punit` with an existing term.

**Comment by TotallyNotChase** [comment]
Indeed, we could do that. But we could do the very same thing now with `popaque` and not change anything ¯\\\_(ツ)\_/¯

**Comment by L-as** [comment]
PUnit is more natural for people to use though

**Comment by t4ccer** [comment]
Not relevant anymore, now `PUnit` is a meaningful type that all V3+ scripts must evaluate to
