### ISSUE TITLE
Explore using plutonomy instead of Shrinker

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#454]
It seems to be better maintained

**Comment by L-as** [comment]
cc @blamario

**Comment by L-as** [comment]
https://github.com/well-typed/plutonomy

**Comment by TotallyNotChase** [comment]
I tried Plutonomy on Plutarch scripts on a project. There were some decent improvements in some scripts, but there were also some losses for some reason.

But in any case, Plutonomy definitely does a bunch of optimizations that Plutarch doesn't right now.

**Comment by AriFordsham** [comment]
It would be interesting to explore the differences.

**Comment by t4ccer** [comment]
`plutonomy` is not maintained anymore, and we have `compileOptimized` that uses optimizer from `plutus-core`

**Comment by SeungheonOh** [comment]
We need some benchmarks on `compileOptimized
