### ISSUE TITLE
Let users choose which golden tests are generated in plutarch-test

### ISSUE THREAD

**Issue by TotallyNotChase** [Plutonomicon/plutarch-plutus#455]
I'm using `plutarch-test` in a project where I don't care about tracking the pre eval UPLC, I only care about the benchmark and the resulting UPLC. I think it'd be nice if we could have a config to choose which goldens are actually generated.

The change would be quite minimal I'd assume, something like-
```hs
data GoldenConf = GoldenConf
  { trackPreEval :: Bool
  -- ^ Whether to track UPLC golden.
  , trackPostEval :: Bool
  -- ^ Whether to track evaluated UPLC golden.
  , trackBench :: Bool
  -- ^ Whether to track benchmark golden.
  }

-- | Like 'pgoldenSpec' but takes a 'GoldenConf' to determine which goldens to track.
pgoldenSpec' :: HasCallStack => GoldenConf -> PlutarchGoldens -> Spec
pgoldenSpec' (GoldenConf {trackPreEval, trackPostEval, trackBench}) map = do
  base <- currentGoldenKey
  let bs = runListSyntax map
      goldenKeys = [(trackPreEval, UPLCPreEval), (trackPostEval, UPLCPostEval), (trackBench, Bench)]
      goldenTests = [ t | (True, t) <- goldenKeys ]
  -- Golden tests
  describe "golden" $ do
    goldenTestSpec base bs `mapM_` goldenTests
  -- Assertion tests (if any)
  let asserts = flip mapMaybe bs $ \(k, v) -> do
        (k,) . (\f -> f (goldenValueEvaluated v) $ goldenValueBenchVal v) <$> goldenValueExpectation v
  unless (null asserts) $ do
    forM_ asserts $ \(k, v) ->
      it (goldenKeyString $ "<golden>" <> k <> "assert") v

```
and `pgoldenSpec` would turn into `pgoldenSpec' $ GoldenConf True True True`

cc @srid

**Comment by srid** [comment]
Sounds good to me. In Plutarch itself we won't be using `pgoldenSpec'`, but user projects can. Is there anything else that should be made configurable in `GoldenConf`?

This would also require adjusting the unused goldens check accordingly.

**Comment by TotallyNotChase** [comment]
Ah yeah. `noUnusedGoldens` would also need to take a `GoldenConf` then.

I'm thinking of putting a `goldenBasePath :: FilePath` in `GoldenConf` as well - that'd allow users to choose where to store the goldens.
