### ISSUE TITLE
Interval API

### ISSUE THREAD

**Issue by rmgaray** [Plutonomicon/plutarch-plutus#464]
At the moment, we have Plutarch versions of `Interval`, `LowerBound`, `UpperBound`, etc. but none of the useful functions available in `plutus-ledger-api`, like `intersects`, `contains` and others. It would be nice to have these (whether in `plutarch` or `plutarch-extras`), since any project that needs to validate time-sensitive operations would have to implement them.

**Comment by MangoIV** [comment]
If anybody wants to take this one, ping me, I've written *some* of them and can probably supply those for upstreaming.

**Comment by rmgaray** [comment]
I'd like to work on this issue (though I will probably do it next week). I will gladly take what you have, @MangoIV

**Comment by MangoIV** [comment]
sure, I'll pm you internally. @rmgaray

**Comment by MangoIV** [comment]
for reference, a gist :3 
https://gist.github.com/MangoIV/c5bcb3e0cf3bdf75dc09d2af835ea7c7
