### ISSUE TITLE
Make `pcon` and `pmatch` predictable

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#482]
`pcon` should always evaluate effects, unless explicitly noted otherwise through `plazy :: Term s a -> Term s a` (errs if used incorrectly).
`pmatch`-bound variables should always be zero-cost and effect-less.
New optimisations should make the above efficient.

**Comment by TotallyNotChase** [comment]
this is complete?

**Comment by L-as** [comment]
Not yet. `pmatch` hasn't been fixed.

**Comment by L-as** [comment]
This was fixed in 1.2.
