### ISSUE TITLE
Add support for Vasil features

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#484]

**Comment by MangoIV** [comment]
I'm not sure whether I should but if it's fine I would like to do this issue, I'm reading into the changes anyway.

**Comment by L-as** [comment]
sure, you should probably wait for me to finish my rework though, because everything has changed

**Comment by MangoIV** [comment]
haha, sounds like a lot of fun.

**Comment by MangoIV** [comment]
because we were talking about it internally, when can I expect to start working on this @L-as

**Comment by L-as** [comment]
Tomorrow probably

**Comment by MangoIV** [comment]
This has been completed
