### ISSUE TITLE
Tag v2 scripts to make it impossible to mix v2 and v1 types and builtins

### ISSUE THREAD

**Issue by MangoIV** [Plutonomicon/plutarch-plutus#503]
Currently it cannot be ensured that people don't use the wrong versions for types and builtins. 
This could be ensure by adding a type parameter for the version and check it in the `compile` function but it would consider a lot of changes afaict.

**Comment by L-as** [comment]
This should be done after 2.0

**Comment by SeungheonOh** [comment]
Will be handled by #640
