### ISSUE TITLE
Haddock (and maybe hoogle) should be hosted somewhere for easier linking in documentation

### ISSUE THREAD

**Issue by TotallyNotChase** [Plutonomicon/plutarch-plutus#55]
We could use github pages.

**Comment by L-as** [comment]
We might also want the guide somewhere.

**Comment by srid** [comment]
@MatthewCroughan has been working on an Hercules CI effects thingy to both generate a website from sources, as well as publish them statically somewhere (such as `gh-pages` branch). We can build on top of that.

**Comment by MatthewCroughan** [comment]
@srid Yes, I have the effect mostly written on the [`add-hercules-ci`](https://github.com/Plutonomicon/plutonomicon/tree/add-hercules-ci) branch of plutonomicon. But I am somewhat blocked by https://github.com/hercules-ci/hercules-ci-effects/issues/45. I will simply make another runner for this repository if this isn't solved soon, however that would mean getting rid of the powerful runner we use, or buying another one of equal spec.

**Comment by L-as** [comment]
#266
