### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by SeungheonOh** [Plutonomicon/plutarch-plutus#557]
We currently have `./bin/format` and `./bin/ghcid` (which doesn't work). Is there any reason for Plutarch not having a Makefile?

**Comment by L-as** [comment]
You want to use flake apps for this.

**Comment by L-as** [comment]
I don't see how a makefile would fit here though?

**Comment by SeungheonOh** [comment]
This is some example of makefile we have: https://github.com/Liqwid-Labs/liqwid-plutarch-extra/blob/main/Makefile 

It's basically what `./bin` is but in one file, organized.

**Comment by MangoIV** [comment]
I agree with Las. Maybe we should use an `app` attribute here; no additional tooling needed.
