### ISSUE TITLE
Output traces in tests

### ISSUE THREAD

**Issue by arjaz** [Plutonomicon/plutarch-plutus#568]
It may be a good idea to show the traces from the execution.
I assume traces are used for the testing purposes only, so it makes sence to me to output them there.

https://github.com/Plutonomicon/plutarch-plutus/blob/a9141ad6dc6ae3aae0697a4ddcb490f3ada1563d/plutarch-test/Plutarch/Test.hs#L74-L83

Maybe have something like that instead:
```haskell
 pshouldBe :: ClosedTerm a -> ClosedTerm b -> Expectation 
 pshouldBe x y = do 
   p1 <- eval $ comp x 
   p2 <- eval $ comp y 
   pscriptShouldBe p1 p2 
   where 
     eval :: Scripts.Script -> IO Scripts.Script 
     eval s = case evalScript s of 
       (Left e, _, traces) -> assertFailure $ "Script evaluation failed: " <> e <> " with traces: " <> show (pretty traces)
       (Right x', _, _) -> pure x' 
```

**Comment by L-as** [comment]
These are the old tests. We use goldens for new things.
