### ISSUE TITLE
Hunit function used by accident

### ISSUE THREAD

**Issue by arjaz** [Plutonomicon/plutarch-plutus#569]
https://github.com/Plutonomicon/plutarch-plutus/blob/a9141ad6dc6ae3aae0697a4ddcb490f3ada1563d/plutarch-test/Plutarch/Test.hs#L82

I think there's an hunit function called by accident, should it be `expectationFailure` from hspec instead?

**Comment by L-as** [comment]
We are still depending on tasty apparently, we should fix that, thanks!

**Comment by t4ccer** [comment]
Testing setup has been refactored
