### ISSUE TITLE
Why does GHC sometimes print Type and sometimes *?

### ISSUE THREAD

**Issue by lemmon-714** [Plutonomicon/plutarch-plutus#587]
This is an uber-detail but such things tend to block me from learning stuff. Referring to the docs, section on Plutarch Types. Will add it myself if I know the answer, thank you.

Also, if I am misusing github with this issue please correct me. Thank you.

**Comment by MangoIV** [comment]
This has nothing to do with Plutarch but rather with GHC. By default GHC shows the kind `Type` as `*`, but it doesn't if `-XNoStarIsType` is enabled, then it prints it as `Type`. You want to look at whether `-XNoStarIsType` is enabled in your repl/ `cabal` file/ at the top of the module.
