### ISSUE TITLE
Missing function `applyArguments` breaks  code in `Run.md` 

### ISSUE THREAD

**Issue by lemmon-714** [Plutonomicon/plutarch-plutus#592]
Tried to find it by using search, checking the [source file](https://github.com/Plutonomicon/plutarch-plutus/blob/master/Plutarch/Api/V1/Scripts.hs) as well as ctrl+f "applyArguments" on each commit for that file. No results. 
1. What am I missing, if any?
2. Please fix it, thank you :) EDIT 2 - not important right now

EDIT [Run.md](https://github.com/Plutonomicon/plutarch-plutus/blob/master/docs/Run.md#evaluation)

**Comment by SeungheonOh** [comment]
Fixed.
