### ISSUE TITLE
POrd, PEq instances for PRationalData seems broken

### ISSUE THREAD

**Issue by peter-mlabs** [Plutonomicon/plutarch-plutus#618]
```
0/1 #< 758566050/758566050 #&& 758566050/758566050 #<= 1/1
```

appears to evaluate to false. The instance is autoderived (while neither `PRational` nor `PlutusTx.Rational` are autoderived), so I'm assuming that either its broken entirely or assumes it is reduced.

Likewise, `1/1 #== 2/2` appears to evaluate to false.

**Comment by SeungheonOh** [comment]
Neither Koz nor I can't reproduce failure on `1/1 #== 2/2`. Plutarch doesn't expose constructor for `PRationalData` and it only allows values to be lifted from PlutusTx.Rational. And all of the constructor of `PlutusTx.Rational` reduces the value given. Both `1/1` and `2/2` will be reduced to `1/1`.

**Comment by SeungheonOh** [comment]
Bug on POrd instance is fixed
