### ISSUE TITLE
`IsList` instances are broken throughout

### ISSUE THREAD

**Issue by kozross** [Plutonomicon/plutarch-plutus#644]
`IsList` requires implementing `fromList`, as well as `toList`. However, in our case, we _cannot_ implement `toList`, as this would require evaluation, which the signature doesn't permit. Thus, throughout the codebase, there are a lot of definitions like this:

```haskell
instance IsList (Term s Whatever) where
   toList = error "unimplemented"
```

This is not an acceptable definition of any type class method, and thus, all such instances must be removed.

**Comment by kozross** [comment]
This will be done as part of #640, as no other problem instances seem to exist.

**Comment by L-as** [comment]
@kozross This will break list literals though AFAICT. You could use RebindableSyntax instead.
