### ISSUE TITLE
Organized round-trip testing for API types

### ISSUE THREAD

**Issue by SeungheonOh** [Plutonomicon/plutarch-plutus#646]
It is crucial to keep Plutrach's ledger types and encoding format aligned with that of plutus-ledger-api. Current test suite does have some setup for testing the roundtrip, but it doesn't cover all API types. 

For new `plutarch-ledger-api`, we need to make sure all api types we are defining are correctly aligned with their plutus counterparts by round-trip test suite.

**Comment by L-as** [comment]
It could be automatically derived.

**Comment by SeungheonOh** [comment]
Yes :+1:
