### ISSUE TITLE
Application from and to perror should be compilable

### ISSUE THREAD

**Issue by SeungheonOh** [Plutonomicon/plutarch-plutus#649]
Currently, below fails at compile, applications that has either perror as function or perror as argument fails at compile time. However, since these have valid UPLC form that can be generated, this should work.  
```hs
compile $ pfoo # perror 
compile $ perror # pfoo
```

**Comment by L-as** [comment]
Why make this not err? This is almost certainly a mistake if ever found in your code. You could have another application operator that doesn't err.

**Comment by SeungheonOh** [comment]
Application from and to an error term is a valid expression in UPLC. It's unreasonable to prevent that by throwing up during compile time, like `plam id # perror` shouldn't fail, it's just `perror` anyways. I'm not sure what mistakes can be made from here.
