### ISSUE TITLE
Feature request: support new `plutus-core` (>= 1.21)

### ISSUE THREAD

**Issue by uhbif19** [Plutonomicon/plutarch-plutus#676]
Seems like the only problem is change of some [lifiting error datatype](https://github.com/IntersectMBO/plutus/commit/dc9f660f7a7a458537ca012d9b113ffab05e0273). AFAIU it does not change semantics, but I am not quite sure.

I make hack to compile plutach by commenting this datatype out and it seem to work for me.

**Comment by kozross** [comment]
Fixed in #677 .
