### ISSUE TITLE
Adding V1 and V2 types

### ISSUE THREAD

**Issue by SeungheonOh** [Plutonomicon/plutarch-plutus#680]
As per @bladyjoker 's note, I found out some valid concerns about deprecating legacy ledger api types: old ledger types can used as datum to some data-providing scripts like oracles. In these cases, user might need to write their own types representing older ledger types.

To address, we need to add back V1 and V2 scripts to `plutrach-ledger-api`.

**Comment by kozross** [comment]
I think as part of this issue, we might as well mirror the structure of `plutus-ledger-api`. I'm already doing it for #655, just with fewer public modules.

**Comment by SeungheonOh** [comment]
Yeah..

We are circling back

**Comment by bladyjoker** [comment]
Thanks folks! @kozross I think it would be convenient to mirror PLA structure, but I don't find it incredibly important as long as we have all the types implemented.

**Comment by L-as** [comment]
Why not make it automatically derived from upstream

**Comment by SeungheonOh** [comment]
We don't have funds for that

**Comment by kozross** [comment]
Done with #690.
