### ISSUE TITLE
CDDL conformance for Conway types

### ISSUE THREAD

**Issue by kozross** [Plutonomicon/plutarch-plutus#685]
Based on [this](https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/conway/impl/cddl-files/conway.cddl), quite a few types make a lot of assumptions (`ChangedParameters` especially) which we don't fully take account of. We definitely need to do this, including in the orphanage.

**Comment by kozross** [comment]
This seems very complicated, so we're kicking it down in priority. Arguably at least with regard to `ChangedParameters`, we're not actually doing any less than PlutusTx, so we're at least no worse.

**Comment by SeungheonOh** [comment]
This should be covered by new property test suite we added.
