### ISSUE TITLE
Tracing functions leave some computation even when compiled with `NoTrace` option

### ISSUE THREAD

**Issue by SeungheonOh** [Plutonomicon/plutarch-plutus#697]
Reported by @bladyjoker , we want tracing function to erase all computation related to that trace message, i.e. `pshow`, when we are compiling with `NoTrace` option. This seems to be not the case currently. Need to investigate and fix if it is not working as we desire.

**Comment by L-as** [comment]
pshow and co. probably need to check if tracing is enabled or not and if so not do anything.

**Comment by t4ccer** [comment]
Closing as impossible to replicate/fixed on staging as of now (ebdba884750f6a8a17639828ecbab2858e1f2347)
