### ISSUE TITLE
`PPOSIXTime` must be able to store negative value

### ISSUE THREAD

**Issue by SeungheonOh** [Plutonomicon/plutarch-plutus#704]
`PPOSIXTime` should be able to store negative integer to store time before 1/1/1970. Currently, instances of `PPOSIXTime` forbids its value going negative

**Comment by L-as** [comment]
Why do you need this?

**Comment by SeungheonOh** [comment]
I don't know @peter-mlabs asked. 

Forbidding negative number for PPOSIXTime was over constraint to why not

**Comment by kozross** [comment]
Are we sure negative times are allowed onchain as such?

**Comment by SeungheonOh** [comment]
Yeah, it seems to work as expected. There's not special invariant on PlutusLedgerApi

**Comment by L-as** [comment]
It's almost always invalid on-chain.

Nevertheless, I don't think there's any good reason to maintain this invariant in Plutarch.
