### ISSUE TITLE
Bug in `pcontains`

### ISSUE THREAD

**Issue by peter-mlabs** [Plutonomicon/plutarch-plutus#705]
It appears that `pcontains` is not working properly.

```hs
ghci> i1
Interval {ivFrom = LowerBound (Finite (POSIXTime {getPOSIXTime = 120})) True, ivTo = UpperBound (Finite (POSIXTime {getPOSIXTime = 129})) False}
ghci> i2
Interval {ivFrom = LowerBound (Finite (POSIXTime {getPOSIXTime = 120})) True, ivTo = UpperBound (Finite (POSIXTime {getPOSIXTime = 129})) True}
ghci> contains i2 i1
True
ghci> plift $ pcontains # pconstant i2 # pconstant i1
False
```

As far as I can tell, it works when the upper bound for both are closed, but not when one is open. We should have the $[120, 129) \subseteq [120, 129]$, but we don't.

**Comment by peter-mlabs** [comment]
Note that this is particularly an issue because of [this](https://github.com/Plutonomicon/cardano-transaction-lib/issues/1041#issuecomment-1280868255). 

Also, we should probably indicate that "gotcha" in the Interval module and haddock comments.

**Comment by L-as** [comment]
Following that comment, if it isn't supported in Plutus, why support it in Plutarch at all?

**Comment by peter-mlabs** [comment]
@L-as Its support in `plutus-ledger-api`, so I think it does make sense for compatibility reasons. 

But I still think that we should have a separate library that actually does what PLA "means" and not what it "does"

**Comment by L-as** [comment]
> `plutus-ledger-api`

Fair reason, but arguably even then you should never use it. You could mark it as deprecated but still fix it.
