### ISSUE TITLE
Run plutus optimization pipeline on compile via `Config` option

### ISSUE THREAD

**Issue by dragospe** [Plutonomicon/plutarch-plutus#710]
See https://github.com/IntersectMBO/plutus/blob/c7eb24c72f3be0e9fd218dc340d297d7c9356530/plutus-core/executables/uplc/Main.hs#L254-L265

These could be run on the raw UPLC after compiling.

**Comment by L-as** [comment]
Why not just do this manually? `Config` is essentially just a `Reader` you can use when generating the code to switch on compile-time options (notably, tracing).
