### ISSUE TITLE
Benchmarks - Utilities for easily diffing performance 

### ISSUE THREAD

**Issue by SeungheonOh** [Plutonomicon/plutarch-plutus#742]
Need something that compares original entries execution budget and script size to new one. It will be similar to golden but more focused on checking performance differences. This should be general enough to be used on down stream project with high performance requirements. 

It should print something like: 
```
| Entry                          | CPU Before | CPU After | CPU Diff | MEM Before | MEM After | MEM Diff | Size Before | Size After | Size Diff |
|--------------------------------+------------+-----------+----------+------------+-----------+----------+-------------+------------+-----------|
| pmatch for Data Encoded types  |       1234 |      1000 | - x.zy%  |       4567 |      4000 | - a.bc % |         123 |        200 | + a.00%   |
| pmatch for Scott Encoded types |       1234 |      1500 | + x.zy%  |       4567 |      4000 | - a.bc % |         123 |        200 | + a.00%   |
```

**Comment by kozross** [comment]
This should probably be designed similarly to `tasty-bench`: effectively we want an `IsTest` implementation.

**Comment by SeungheonOh** [comment]
`tasty` sounds good. We don't need to write benchmark dsl here
