### ISSUE TITLE
Convert to PLiftable

### ISSUE THREAD

**Issue by kozross** [Plutonomicon/plutarch-plutus#749]
We need to replace all uses, and instances, of `PUnsafeLiftDecl` and `PConstantDecl` with `PLiftable`. This has to be done 'all at once', and may require additional definitions or bits. Instances will be the primary work, because `pconstant` and `plift` have the same semantics (and signatures) modulo minor definition changes.

**Comment by t4ccer** [comment]
Closed in https://github.com/Plutonomicon/plutarch-plutus/pull/753
