### ISSUE TITLE
Separate UPLC optimization from compilation

### ISSUE THREAD

**Issue by kozross** [Plutonomicon/plutarch-plutus#784]
What we need is something like `optimize :: forall a s . (forall s' . Term s' a) -> Term s a`. This will allow us to use optimization with things like `Plutarch.Pretty`, for instance.

**Comment by L-as** [comment]
You can just wrap it in a term but it’s probably the plutarch pretty API that’s incorrect.

**Comment by kozross** [comment]
The `Plutarch.Pretty` API is the entire motivation for this.
